### ISSUE TITLE
PSU not displayed in Neo-Babylonian glossary of Nappahu

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#102]
**Project:** nappahu
**Server:** build-oracc

In the `akk-x-neobab.glo` file of nappahu, the following PSU have been entered:
`@entry šupāl šēpī [footstool] N`
`@parts šupālu[depression]N šēpu[foot]N`
`@form {giš}šu-pal_GIR₃.II $šupāl $šēpī`
`@sense N footstool`
`@end entry`

The project has been rebuilt and no errors are reported in the oracc.log regarding this PSU.

**Expected result:**
The PSU should appear in the Neo-Babylonian glossary; see [http://build-oracc.museum.upenn.edu/nappahu/cbd/akk-x-neobab/SH.html](url).

**Actual result:**
The PSU fails to appear. See the image.
![missing_psu](https://user-images.githubusercontent.com/19565350/44191371-70076a80-a12b-11e8-8b9f-feea71b69362.png)

**Note:** This is not an isolated instance. The same issue has been observed by various members of the MOCCI team in RIAo, RIBo, and Suhu.

**Comment by stinney** [comment]
This is fixed.  For the technically minded, it stems from a test failure where an incoming form/signature is being compared to a the form/signature that is loaded by the lemmatizer: where the incoming form has no EPOS, the test was failing unless the lemmatize's form had the same POS and EPOS.  I've disabled the test so now if an incoming form has no EPOS (normally the case for PSUs) it's treated as a wildcard that matches any EPOS in the lemmatizer's form.

I don't think this should have any negative effects elsewhere in the lemmatizer--even if it does, the test was wrong so anything depending on it will have to be fixed in some other way.
