### ISSUE TITLE
Old Persian lemmatisation fails on split words

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#61]
Users are unable to lemmatise Old Persian words split between two lines.
![screen shot 2016-12-09 at 14 52 19](https://cloud.githubusercontent.com/assets/19565350/21051168/3e18aa48-be1f-11e6-9443-c2d53f41bd1d.png)

As formatted above, the entry appears in the glossary as:
`@entry Xerxes_I [king of Persia] RN`
`@form x-š-y-a- %peo $Xšayaršā`
`@sense RN king of Persia`
`@end entry`

and not as the expected  
`@entry Xerxes_I [king of Persia] RN`
`@form x-š-y-a-r-š-a %peo $Xšayaršā`
`@sense RN king of Persia`
`@end entry`

Adding a semi-colon (as one does in Akkadian and Sumerian texts), does not change the functionality.

`1. x-š-y-a-;`
`2. -r-š-a :`
Generate the error: 
`xerxesI02.atf:9:Q007206: XML error: attribute ^headform not allowed`
`xerxesI02.atf:9:Q007206: XML error: attribute ^contrefs not allowed`
`xerxesI02.atf:12:Q007206: XML error: element http://oracc.org/ns/norm/1.0^s not allowed`
`xerxesI02.atf:12:Q007206: XML error: element http://oracc.org/ns/norm/1.0^s not allowed`
`xerxesI02.atf:12:Q007206: XML error: element http://oracc.org/ns/norm/1.0^s not allowed`

`1. x-š-y-a;-`
`2. -r-š-a :`
Generates the error `xerxesI02.atf:9: (lem) no FORM `x-š-y-a'; 1 match for Xerxes_I[king of Persia]RN in glossary ario:peo`

At present, Oracc is unable to lemmatise words split over two lines. This represents a high percentages of words that cannot be lemmatised.

**Comment by D-K-E** [comment]
Hi,      
First of all great project, i am really enthusiastic about what's going on here ! As for the word divisions, I was actually working on the same issue for my [c-atf-feature-extractor](https://github.com/D-K-E/c-atf-feature-extractor). This issue persist not only for old persian texts, but also for elamite texts of Achaemenid Empire. 
Furthermore in elamite royal inscriptions of achaemenid period rarely some complex signs, like ANSZE, are divided as well. I think i can handle word divisions with the feature extractor with relative ease. I'd need to implement the same algorithm that i had used for detecting another language occurrences. Roughly it would go out as the following for c-atf texts, you might need to arrange it so that it would be applicable to ORACC-ATF:       
 * A divided word would consist of the following pattern \s\w.*-\n\d+\.\s\w.*?\s, in c-atf that is some word that terminates with a "-" and a newline character followed by a line number plus a dot plus a single space plus the rest of the word.     
 * They need to be handled either at the part level or text level, that is either between parts declared with @ like @column 2 or directly at the text level, which should contain no division whatsoever. The first one is easy to understand, part is bigger than line, since a divided word is also symbolically bigger than a line, since it is dispersed into two lines, it can be handled at the part level. However i am hesitating because in really small tablets, like tablets found in the fortification archive of Persepolis, one might find words divided across the logical parts, like obverse, reverse. However handling them at the text level would complicate **a lot** the indexation of the words, thus might be an overkill, but i have hunch that in the end i would have to settle with that option.    
 * Thus the exact algorithm is somewhere along the following lines for the part level:
 + Match the above mentioned regex in the string representation of the part.
 + Take the line number from the matched divided word.
 + Subtract 1 from the line number for finding the previous line number.
 + The gizmo: a divided word is the last term preceded by a space in the previous line number, and the first term followed by space after the line number.
 + After lines are splited to words by spaces, one uses the gizmo for identifying and thus working with a divided word.

Hope this helps,    
I will make another issue for divided signs.    
All the Best

**Comment by stinney** [comment]
This was fixed in Dec 16 so I'm closing it.

@D-K-E thanks for your very thoughtful comments.  We have corrected the documentation to reflect the situation with atf continuation lines: the rule is that you end the line with hyphen and semi-colon  (-;) and then start the next line with a hyphen (-).  This now lemmatizes and indexes correctly (the searching was only fixed today).  For ansze in Elamite, we use ansze@d rather than dividing the actual sign.  We don't support splitting of arbitrary signs across a line boundary, but we could add additional special cases if necessary.
