### ISSUE TITLE
ATF modes fail on PC: LMU-server

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#88]
Nathan is now working from home days a week. Until Wednesday of last week, he had no problems. Since then he can no longer use any of the ATF modes (Check ATF, Lemmatizer Buffer, etc.).
Server: oracc.ub.uni-muenchen.de
Platform: PC (Windows 10)
Steps:
1. login to RIAo on oracc.ub.uni-muenchen.de and navigate to the 00atf folder.
2. Open, for example, ShalmaneserIII026.atf.
3. Run `Check ATF` or `lemmatise buffer`.
Expected results: The ATF functions should work.
Actual result: an `Error during request 500` occurs.
He has tried from home and at the office. No issues occur on a Mac.

**Comment by niekveldhuis** [comment]
Jamie,
The error 500 message appears when the wrong server is mentioned in the oracc-init.el file. Have you checked that with Nathan? I assume it is right, because you said it all worked a few weeks ago - but it may be worth checking. I do not have such problems on any of my Windows computers so far.

**Comment by jnovotny-lmu** [comment]
The oracc-init.el was not updated. Thus, not a bug and closing Thanks for the suggestion Niek.
