### ISSUE TITLE
grouping: pointy/round brackets, checking and lemmatizing

### ISSUE THREAD

**Issue by niekveldhuis** [oracc/oracc#90]
It seems that the checker currently ignores problems with pointy/round brackets. Once such a problem is in, the checker ignores all problems and will judge a file "clean". When this "clean" file is lemmatized the lemmatizer erases the file but does not replace it with a lemmatized version.
Example: (derived from real-life example):
&P413975 = LKA 63
#project: rnta
#atf: lang akk-x-stdbab
#atf: use unicode
#atf: use math
@tablet
@obverse
18'. x# [...]-ša kit-pu#-tu ṣa-bur-ta še#-e#-ʾu!(-x)
$<single>ruling
23'. [i]-ru#ur# [X X]{MEŠ} UN#<{MEŠ}>-šu₂-[nu]

Checker: ATF file lka63.atf is clean.

After repairing the bracket issue in 18
Checker: 
lka63.atf:10: <single>ruling: bad character in $-line
lka63.atf:11: unknown token at: ur# [X X]{MEŠ} UN#<{MEŠ}>-šu₂-[nu]
ATF processor ox issued 2 warnings and 0 notices

Trying to lemmatize before repairing the bracket issue in 18:
file is wiped
messages:
>let: Wrong type argument: char-or-string-p, nil
>Mark set
It seems that the checker allows the form  UN#<{MEŠ}>-šu₂-[nu] - I wonder whether that should be  UN#{<MEŠ>}-šu₂-[nu]

**Comment by stinney** [comment]
The symptom of an apparently clean file followed by lemmatization failure derives from a new issue with the build servers that I have no fix for at present: some ATF processor crashes are caught by the handler that issues the message about a crash; others are not caught by the handler.   In this case, the checker is silently crashing, but the lemmatizer is being noisier.

I've fixed the underlying but in 18, which is that u!(-x) was being parsed as the the parens were the stuff corrected, but you were trying to say "there may be an x following the u!" (I think).  Now, the parser assumes the ! has no corrected grapheme after it in parens, so you correctly get the complaint about the sequence ( followed by - : with ATF we need to say u!-(x) for this.

The other line, 23', is a red herring.  UN<{ME}> and UN{<ME>} produce the same XML code--they are saying the same thing ("I'm supplying a determinative logogram ME here").  There is an error in the line, though--ru#ur# is missing a hyphen: ru#-ur#. 

Closing this because the crash is fixed.
