### ISSUE TITLE
oracc serve fails to rebuild public-facing server

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/oracc#93]
Run `oracc serve` for any project on the build-oracc or oracc.ub-uni-muenchen, wait the appropriate time, and check the changes on oracc.museum.upenn.edu.
Expected result: The changes made are now publicly accessible.
Actual result: The changes are not made public.

**Comment by stinney** [comment]
This may have stemmed from something which I finally saw in action a week or so ago and then fixed.  It used to be the case that the public server could retrieve a project during the creation of the served archive file.  Then the update would file because the archive was corrupt.  I've rewritten the serve script so now it creates the served archive in a separate file and only moves it into the name the public server expects to find after it is complete.
